episode: 100
unknown_speakers:
- speaker: Guest_Unknown
  total_time: 181.5
  segments:
  - stime: 7288.24
    etime: 7317.97
    text: 'Ну что хвалить? Спасибо вам большое. Благодаря вам я обратил внимание на
      айфон. Сейчас жду, когда он появится у нас. Хотя все-таки в мечтах купить iPod
      Touch. В общем, большое-большое спасибо вам. По '
    duration: 29.730000000000473
  - stime: 6971.67
    etime: 7000.98
    text: Меня как-то очень криво слышу у всех ведущих. Действительно, хочу поздравить
      с сотым выпуском, как и все остальные, пожелать еще сотен, еще тысяч выпусков
      в будущем. Пожелать удачи в частных подкастах
    duration: 29.30999999999949
  - stime: 6162.67
    etime: 6189.87
    text: Многомиллионную аудиторию, чтобы рассказать, как я люблю радио. Я слушаю
      его буквально только один месяц и мне уже симпатизирует то, о чем вы разговариваете.
      Хотя порой не достает профессиональных мне
    duration: 27.199999999999818
reference_speakers:
- speaker: Bobuk
  total_time: 1712.8
  reference_segment:
    stime: 5065.16
    etime: 5134.69
    text: Вы поймите, на самом деле, когда был 62 выпуск, я был очень занят, я не
      мог подойти, просто я не мог записываться. Дело все в том, что в следующем выпуске
      появилась оляпка. Я вам еще раз напоминаю. Не
    duration: 69.52999999999975
- speaker: Umputun
  total_time: 3264.5
  reference_segment:
    stime: 7351.44
    etime: 7406.58
    text: Молодец. Хороший праздник. Подожди. Спасибо слушателю. У нас тут повалились
      звонки. Спасибо еще раз Терминатор, он же Пингвинатор, он же губернатор Калифорнии.
      Когда вы сюда звоните, я вас в эфир сраз
    duration: 55.14000000000033
- speaker: Gray
  total_time: 1119.6
  reference_segment:
    stime: 5304.76
    etime: 5397.61
    text: 'Очень хочу вас поздравить с вашим сотым выпуском. С недавнего времени,
      с выпуска 80-го, я стал слушать ваш подкаст. До этого времени баловался только
      блогами. Да и то на это времени не очень хватало. '
    duration: 92.84999999999945
- speaker: Olyapka
  total_time: 807.1
  reference_segment:
    stime: 7079.92
    etime: 7129.99
    text: 'Здравствуйте, меня зовут Айрат. Я бы хотел поздравить вас с юбилеем, с
      сотым выпуском. И пожелать вам много-много хороших выпусков, чтобы у вас все
      было хорошо, и аудитория росла по экспоненте, и все '
    duration: 50.06999999999971
- speaker: Gimlis
  total_time: 76.5
  reference_segment:
    stime: 5511.81
    etime: 5563.86
    text: Ну, если не учитывая то, что я сейчас второй раз в Радио Т попадаю, до этого
      я был еще парочку раз после шоу, которое называется «Авторпати», которое мне
      незаслуженно приписали, хотя я начинал все это
    duration: 52.04999999999927
segments_to_extract:
- speaker: Bobuk
  stime: 5065.16
  etime: 5134.69
  duration: 69.52999999999975
  type: reference
- speaker: Gray
  stime: 5304.76
  etime: 5397.61
  duration: 92.84999999999945
  type: reference
- speaker: Gimlis
  stime: 5511.81
  etime: 5563.86
  duration: 52.04999999999927
  type: reference
- speaker: Guest_Unknown
  stime: 6162.67
  etime: 6189.87
  duration: 27.199999999999818
  type: unknown
- speaker: Guest_Unknown
  stime: 6971.67
  etime: 7000.98
  duration: 29.30999999999949
  type: unknown
- speaker: Olyapka
  stime: 7079.92
  etime: 7129.99
  duration: 50.06999999999971
  type: reference
- speaker: Guest_Unknown
  stime: 7288.24
  etime: 7317.97
  duration: 29.730000000000473
  type: unknown
- speaker: Umputun
  stime: 7351.44
  etime: 7406.58
  duration: 55.14000000000033
  type: reference
comparisons:
- unknown: Guest_Unknown
  compare_with:
  - Bobuk
  - Umputun
  - Gray
  - Olyapka
  - Gimlis
