episode: 150
unknown_speakers:
- speaker: Guest_Unknown
  total_time: 1208.1
  segments:
  - stime: 2977.57
    etime: 3048.61
    text: Привет, любимый Радио-Т. Привет, Умпутун. Привет, Бобук. Привет, Грей. И,
      надеюсь, привет, Маринка. Пожалуй, стоит сказать, насколько сильно мы вас любим.
      По крайней мере, я. Я вас слушаю давно-таки д
    duration: 71.03999999999996
  - stime: 5377.97
    etime: 5427.53
    text: 'Спасибо. Всем здравствуйте. Очень благодарен за возможность вот так вот
      очно, можно сказать, поздравить всех вас. К сожалению, я не такой давний слушатель
      вашего подкаста, как многие другие. Узнал от '
    duration: 49.55999999999949
  - stime: 4685.36
    etime: 4734.15
    text: Да, я понимаю. Нет, хвалить вас есть за что, потому что очень интересно
      слушать людей, которые понимают в программировании, которые понимают в IT. Например,
      для новичков это вообще полезно, потому что
    duration: 48.789999999999964
reference_speakers:
- speaker: Bobuk
  total_time: 1841.0
  reference_segment:
    stime: 6388.35
    etime: 6440.53
    text: Подожди, Мариночка, давай я вам свою мысль выскажу, и сразу после этого
      ты. Я просто хотел сказать, что вы обратите внимание, насколько все-таки гости,
      которых мы подобрали, а на самом деле, которые с
    duration: 52.17999999999938
- speaker: Umputun
  total_time: 1995.2
  reference_segment:
    stime: 7590.07
    etime: 7647.02
    text: Ух ты. Интересный подкаст. Мы, конечно, о нем поговорим сразу. Как только
      завершим сегодняшнее самовосхваление, самолюбование, я думаю, можно планку считать
      достигнутой. Мы взяли эту величину, постави
    duration: 56.95000000000073
- speaker: Marin_k_a
  total_time: 643.6
  reference_segment:
    stime: 6477.54
    etime: 6534.18
    text: Хорошо. Я хочу поздравить вас, дорогие, в первую очередь, Умпутун, Бобук,
      потом уже присоединился Грей, также была, ну, до Грея была Аляпка, потом еще
      Лавале. Я вас слушаю, наверное, уже года два. И п
    duration: 56.64000000000033
- speaker: Gray
  total_time: 919.8
  reference_segment:
    stime: 3470.84
    etime: 3542.16
    text: Я в детстве так очень любил, когда шло какое-нибудь очередное торжественное
      прощение от сына. центрального комитета коммунистической партии, включить еще
      и вот к телевизору радио и вот получать его эф
    duration: 71.31999999999971
- speaker: Rosnovsky
  total_time: 141.3
  reference_segment:
    stime: 434.96
    etime: 479.95
    text: 'Ну, во-первых, я прославился, собственно, благодаря «Радио Ти». Не все
      знают, не все меня знают, так я прославился благодаря «Радио Ти». На самом деле
      я просто преклоняюсь и снимаю шляпу, потому что, '
    duration: 44.99000000000001
- speaker: EldarMurtazin
  total_time: 151.3
  reference_segment:
    stime: 975.57
    etime: 1029.1
    text: Многие лета. Мне кажется, то, что вы делаете, ребята, получается у вас отлично.
      И главное – не останавливаться. Чем больше новых людей будет при неизменном
      составе основных ведущих, тем будет лучше. И
    duration: 53.52999999999986
segments_to_extract:
- speaker: Rosnovsky
  stime: 434.96
  etime: 479.95
  duration: 44.99000000000001
  type: reference
- speaker: EldarMurtazin
  stime: 975.57
  etime: 1029.1
  duration: 53.52999999999986
  type: reference
- speaker: Guest_Unknown
  stime: 2977.57
  etime: 3048.61
  duration: 71.03999999999996
  type: unknown
- speaker: Gray
  stime: 3470.84
  etime: 3542.16
  duration: 71.31999999999971
  type: reference
- speaker: Guest_Unknown
  stime: 4685.36
  etime: 4734.15
  duration: 48.789999999999964
  type: unknown
- speaker: Guest_Unknown
  stime: 5377.97
  etime: 5427.53
  duration: 49.55999999999949
  type: unknown
- speaker: Bobuk
  stime: 6388.35
  etime: 6440.53
  duration: 52.17999999999938
  type: reference
- speaker: Marin_k_a
  stime: 6477.54
  etime: 6534.18
  duration: 56.64000000000033
  type: reference
- speaker: Umputun
  stime: 7590.07
  etime: 7647.02
  duration: 56.95000000000073
  type: reference
comparisons:
- unknown: Guest_Unknown
  compare_with:
  - Bobuk
  - Umputun
  - Marin_k_a
  - Gray
  - Rosnovsky
  - EldarMurtazin
