episode: 284
unknown_speakers:
- speaker: SPEAKER_02
  total_time: 86.5
  segments:
  - stime: 1404.87
    etime: 1421.15
    text: Нет, здесь просто уже открыты, скажем, темы какие-то, и это весьма удобно.
      Видео-встречи я для себя открыл, потому что изменился интерфейс того же самого
      Google Plus, и стало удобнее, скажем, я только
    duration: 16.2800000000002
  - stime: 1475.99
    etime: 1490.39
    text: Вопрос, конечно, спорный, но это, не знаю, может просто больше опыта появилось,
      но судя по моему опыту, люди меньше жалуются, просто реже приходят ездить куда-то
      в командировки для исправления ошибок.
    duration: 14.400000000000091
  - stime: 1430.32
    etime: 1440.71
    text: Да, я программист. Ну, в последнее время программировал на C++, до этого
      программировал на Python и Perl'е в первое время, но потом от этого отказался.
    duration: 10.3900000000001
- speaker: SPEAKER_01
  total_time: 211.8
  segments:
  - stime: 2316.41
    etime: 2342.49
    text: Ну нет, у меня вот есть знакомая ситуация. Тут народ очень, скажем, неохотно
      переходит в облако. То есть главный аргумент, что я же не знаю, где мои данные
      находятся, скажем так. Я не могу контролиров
    duration: 26.079999999999927
  - stime: 2116.34
    etime: 2136.8
    text: 'Да, на испанском языке. Для людей, которые старше 25 лет, сильно проще
      тест, чем для студентов стандартных. А для людей старше, чем 45, еще проще.
      Ну, и вас попросят сдать вот эти экзамены, и все, на '
    duration: 20.460000000000036
  - stime: 2684.58
    etime: 2704.98
    text: Прямо на первом курсе начинают давать структуру процессоров, потом на втором
      курсе, ну, там, скажем так, базы данных, я смотрю, структура данных, алгоритмы.
      Ну, и... Я еще не знаю, что это такое, опер
    duration: 20.40000000000009
reference_speakers:
- speaker: Bobuk
  total_time: 1317.4
  reference_segment:
    stime: 6698.48
    etime: 6752.97
    text: 'Это такой отдельный, что ли, не SSH, а как это сказать, такой ремонт доступа
      клиент, который инициализируется по SSH-у, А после этого посылает пакетики через
      UDP, просто для того, чтобы быстрее было. '
    duration: 54.49000000000069
- speaker: Umputun
  total_time: 3611.0
  reference_segment:
    stime: 3294.95
    etime: 3411.4
    text: Это типичная проблема умных систем. После того, как ты напишешь умную систему,
      в которой чуть ли не искусственный интеллект из всех щелей лезет, то быстро
      убеждаются, что поддерживать такое в общем сл
    duration: 116.45000000000027
- speaker: Gray
  total_time: 1472.8
  reference_segment:
    stime: 600.52
    etime: 668.41
    text: Было, было. И про антивирус для Интела, и про телефон Моторола для Гугла.
      Совершенно стандартная штука. Да, собственно, тема-то чего? Значит, на этой
      неделе Фейсбук путем записи в личном блоге Цукербе
    duration: 67.88999999999999
segments_to_extract:
- speaker: Gray
  stime: 600.52
  etime: 668.41
  duration: 67.88999999999999
  type: reference
- speaker: SPEAKER_02
  stime: 1404.87
  etime: 1421.15
  duration: 16.2800000000002
  type: unknown
- speaker: SPEAKER_02
  stime: 1430.32
  etime: 1440.71
  duration: 10.3900000000001
  type: unknown
- speaker: SPEAKER_02
  stime: 1475.99
  etime: 1490.39
  duration: 14.400000000000091
  type: unknown
- speaker: SPEAKER_01
  stime: 2116.34
  etime: 2136.8
  duration: 20.460000000000036
  type: unknown
- speaker: SPEAKER_01
  stime: 2316.41
  etime: 2342.49
  duration: 26.079999999999927
  type: unknown
- speaker: SPEAKER_01
  stime: 2684.58
  etime: 2704.98
  duration: 20.40000000000009
  type: unknown
- speaker: Umputun
  stime: 3294.95
  etime: 3411.4
  duration: 116.45000000000027
  type: reference
- speaker: Bobuk
  stime: 6698.48
  etime: 6752.97
  duration: 54.49000000000069
  type: reference
comparisons:
- unknown: SPEAKER_02
  compare_with:
  - Bobuk
  - Umputun
  - Gray
- unknown: SPEAKER_01
  compare_with:
  - Bobuk
  - Umputun
  - Gray
