episode: 350
unknown_speakers:
- speaker: SPEAKER_01
  total_time: 172.7
  segments:
  - stime: 648.52
    etime: 687.76
    text: Они переквалифицировались. Вместо того, что раньше они делали, сейчас они
      больше бегают к людям, которые либо что-то не могут сделать с базой, либо с
      приложением на базе Java, либо еще какие-нибудь ст
    duration: 39.24000000000001
  - stime: 776.06
    etime: 812.83
    text: У нас в планово-экономическом отделе есть девушка, вот она очень классно
      шарит, и если мы два ИТшника и те два... системных администраторов, переквалифицированных,
      заняты, то мы спокойно к ней можем о
    duration: 36.770000000000095
  - stime: 702.82
    etime: 724.83
    text: Для них это расширение, по-моему, каких-то своих базовых знаний. Я пока
      с ними был в одном отделе, потом меня перевели, оставили как раз на таких более
      простых вещах, а с ними я так только уже общаюсь
    duration: 22.00999999999999
- speaker: SPEAKER_02
  total_time: 248.3
  segments:
  - stime: 1131.6
    etime: 1189.99
    text: Нет, нет, Helpdesk нет. У нас изначально была группа e-mail. Все посылают
      e-mail на один адрес и там отвечают. Соответственно, моя система была установить
      Helpdesk систему, то есть веб-приложение. И ч
    duration: 58.3900000000001
  - stime: 1074.11
    etime: 1119.66
    text: Тут уникальное, просто нет такого, чтобы вот эта конфигурация должна работать.
      Недавно члены нашей команды, кстати, в Яндекс приезжали, рассказывали, как собирать
      данные на очень большой скорости, это
    duration: 45.55000000000018
  - stime: 1212.87
    etime: 1249.83
    text: Тут есть разделение онлайн и оффлайн. Онлайн отвечает за сбор информации
      и сохранение на диске, то есть, соответственно, на файлах сервера. Есть такая
      система кастер, которая все еще работает на тейпа
    duration: 36.960000000000036
reference_speakers:
- speaker: Umputun
  total_time: 3324.0
  reference_segment:
    stime: 6563.59
    etime: 6716.48
    text: Суть статьи, которую мы обсуждаем, и я с ней полностью согласен, что для
      Microsoft вот такая переорганизация под Apple модель, а, собственно, об этом
      речь идет. Они хотят стать функциональной организа
    duration: 152.88999999999942
- speaker: Marin_k_a
  total_time: 855.3
  reference_segment:
    stime: 3835.24
    etime: 3870.37
    text: И он говорит, сразу после того, как я это все отправил, буквально через
      какое-то очень короткое время, Apple закрыла портал. Насколько истинно его признание,
      в общем-то, пока непонятно, потому что ник
    duration: 35.13000000000011
- speaker: Gray
  total_time: 1596.9
  reference_segment:
    stime: 6841.1
    etime: 6994.27
    text: В принципе, можно легко рассказать, почему. Это, наверное, неизбежно для
      большой компании, потому что когда-то, когда у нас была небольшая компания,
      когда это были какие-то сотни человек, а потом даже
    duration: 153.17000000000007
- speaker: Ksenks
  total_time: 459.4
  reference_segment:
    stime: 1442.58
    etime: 1463.97
    text: 'Нет, ну почему? Бывают, мне кажется, разные. То есть тот, кто пишет, там
      можно с какой-нибудь программисткой, которая с утра там на PHP, вечером там
      еще на чем-нибудь таком же. Ну то есть как бы если '
    duration: 21.3900000000001
- speaker: EldarMurtazin
  total_time: 288.1
  reference_segment:
    stime: 3661.31
    etime: 3690.2
    text: Вообще на всех А часто там еще этот, как он называется Арашатор Или как-то
      еще Нет, нет, нет, это не про устройство Это просто вот такая электрическая
      зубная щетка Но неохота покупать две И покупают о
    duration: 28.889999999999873
segments_to_extract:
- speaker: SPEAKER_01
  stime: 648.52
  etime: 687.76
  duration: 39.24000000000001
  type: unknown
- speaker: SPEAKER_01
  stime: 702.82
  etime: 724.83
  duration: 22.00999999999999
  type: unknown
- speaker: SPEAKER_01
  stime: 776.06
  etime: 812.83
  duration: 36.770000000000095
  type: unknown
- speaker: SPEAKER_02
  stime: 1074.11
  etime: 1119.66
  duration: 45.55000000000018
  type: unknown
- speaker: SPEAKER_02
  stime: 1131.6
  etime: 1189.99
  duration: 58.3900000000001
  type: unknown
- speaker: SPEAKER_02
  stime: 1212.87
  etime: 1249.83
  duration: 36.960000000000036
  type: unknown
- speaker: Ksenks
  stime: 1442.58
  etime: 1463.97
  duration: 21.3900000000001
  type: reference
- speaker: EldarMurtazin
  stime: 3661.31
  etime: 3690.2
  duration: 28.889999999999873
  type: reference
- speaker: Marin_k_a
  stime: 3835.24
  etime: 3870.37
  duration: 35.13000000000011
  type: reference
- speaker: Umputun
  stime: 6563.59
  etime: 6716.48
  duration: 152.88999999999942
  type: reference
- speaker: Gray
  stime: 6841.1
  etime: 6994.27
  duration: 153.17000000000007
  type: reference
comparisons:
- unknown: SPEAKER_01
  compare_with:
  - Umputun
  - Marin_k_a
  - Gray
  - Ksenks
  - EldarMurtazin
- unknown: SPEAKER_02
  compare_with:
  - Umputun
  - Marin_k_a
  - Gray
  - Ksenks
  - EldarMurtazin
