episode: 373
unknown_speakers:
- speaker: SPEAKER_01
  total_time: 1963.1
  segments:
  - stime: 4903.24
    etime: 5019.31
    text: Понимаешь, вот смотри, как это выглядит с моей стороны, да, то есть, если
      брать несколько лет назад, да, когда появилась эта идея, там, юнит тестирования,
      там, G-Unit, который мигрировал на всякие язы
    duration: 116.07000000000062
  - stime: 9569.92
    etime: 9634.13
    text: 'Нет, а потому что вот как бы у тебя, ну, даже если растет по чуть-чуть,
      да, то инфляция там, ну, не знаю, 10%, реальная 15-20%, да, и работодателю объяснить,
      что надо повышать там, ну, индексировать, '
    duration: 64.20999999999913
  - stime: 5120.09
    etime: 5181.85
    text: И суть. Там... Даже если нету каких-то специальных конструкций, которые
      фреймворк, там не знаю, какое-то взаимодействие, не знаю, с памятью, там бывает
      такое магическое сочетание параметров, когда там
    duration: 61.76000000000022
reference_speakers:
- speaker: Bobuk
  total_time: 2685.8
  reference_segment:
    stime: 5194.91
    etime: 5242.28
    text: Да дело не в фигне, дело в том, что это такой, это типичный подход, сейчас
      я аккуратно скажу, сейчас попытаюсь аккуратно выразиться все-таки. Это некоторое
      проявление слабости, которое свойственно нам
    duration: 47.36999999999989
- speaker: Umputun
  total_time: 4275.9
  reference_segment:
    stime: 7991.32
    etime: 8088.12
    text: Конечно, потому что я знаю, что такой вопрос где-то кто-то уже задал. И
      второй способ, вот когда вчера я ходил, не далее, как вчера, у меня была такая
      суровая проблема, вообще конкретно суровая пробле
    duration: 96.80000000000018
- speaker: Marin_k_a
  total_time: 563.8
  reference_segment:
    stime: 10322.34
    etime: 10374.91
    text: 'Там все сложнее, не с квадратными метрами, но если ты говоришь просто об
      уровне жизни, ну, примерно, что... Как у всех, давай, про этот уровень жизни.
      Да, уровень жизни какой-то примерно средний, вот '
    duration: 52.56999999999971
- speaker: Gray
  total_time: 357.5
  reference_segment:
    stime: 10143.34
    etime: 10178.67
    text: Я тебе могу сказать, путем долгих наблюдений над IT-компаниями, я тебе могу
      сказать только одно. Вот тот факт, что в IT себестоимость продукта каждого конкретного
      следующего очень низка, оно только пр
    duration: 35.32999999999993
- speaker: Ksenks
  total_time: 353.2
  reference_segment:
    stime: 9192.52
    etime: 9222.25
    text: Да, нет, я тоже, у меня абсолютно противоположный опыт. Это, мне кажется,
      как раз жена айтишника может привести в идеальный порядок двухкомнатную квартиру
      за 2-3 часа, потом айтишник... Особенно после
    duration: 29.729999999999563
segments_to_extract:
- speaker: SPEAKER_01
  stime: 4903.24
  etime: 5019.31
  duration: 116.07000000000062
  type: unknown
- speaker: SPEAKER_01
  stime: 5120.09
  etime: 5181.85
  duration: 61.76000000000022
  type: unknown
- speaker: Bobuk
  stime: 5194.91
  etime: 5242.28
  duration: 47.36999999999989
  type: reference
- speaker: Umputun
  stime: 7991.32
  etime: 8088.12
  duration: 96.80000000000018
  type: reference
- speaker: Ksenks
  stime: 9192.52
  etime: 9222.25
  duration: 29.729999999999563
  type: reference
- speaker: SPEAKER_01
  stime: 9569.92
  etime: 9634.13
  duration: 64.20999999999913
  type: unknown
- speaker: Gray
  stime: 10143.34
  etime: 10178.67
  duration: 35.32999999999993
  type: reference
- speaker: Marin_k_a
  stime: 10322.34
  etime: 10374.91
  duration: 52.56999999999971
  type: reference
comparisons:
- unknown: SPEAKER_01
  compare_with:
  - Bobuk
  - Umputun
  - Marin_k_a
  - Gray
  - Ksenks
