episode: 382
unknown_speakers:
- speaker: SPEAKER_02
  total_time: 403.6
  segments:
  - stime: 2156.13
    etime: 2230.4
    text: 'Хотел бы добавить, если можно. У нас, допустим, я-то был программист в
      той компании и... Значит, если мы хотели добавить какой-то патч или заобновить
      текущую систему, то обычно мы сделали свою работу '
    duration: 74.26999999999998
  - stime: 1581.82
    etime: 1639.28
    text: Ну, я работал сам-то в Barclay, не буду раскрывать слишком много деталей,
      понимаете, почему, но у них-то не один дата-центр, у них действительно, ну,
      на всех почти континентах свой дата-центр, у них л
    duration: 57.460000000000036
  - stime: 1665.09
    etime: 1711.58
    text: Ну, может так. Тут, в принципе, главное определиться. Не обязательно, конечно,
      все будет храниться на физических серверах. Есть приватные клауды. Есть там
      IaaS-инженеры, которые заботятся об этом клау
    duration: 46.49000000000001
reference_speakers:
- speaker: Umputun
  total_time: 3269.2
  reference_segment:
    stime: 632.39
    etime: 717.94
    text: Чем-то другим, да. Лаптем. Лаптем. Умница. Точно. Умница, Сван. Вот смотри,
      дорогой, у нас есть банки. Знаешь, банки, они параноики по самое не могу. Они
      говорят, делайте, что хотите, но никакие данны
    duration: 85.55000000000007
- speaker: Marin_k_a
  total_time: 639.1
  reference_segment:
    stime: 4877.51
    etime: 4918.15
    text: 'И идея в том, что пофиксировалось все тем, что они сделали новую метку
      go to fail. Это забавно, что то же самое, как у Apple. Ну и вообще, мне кажется,
      go to как-то еще больше дискредитировал себя, и '
    duration: 40.63999999999942
- speaker: Ksenks
  total_time: 481.5
  reference_segment:
    stime: 6002.44
    etime: 6027.3
    text: Потому что уже такое произошло, насколько я поняла, в Хабаровске. Я вообще
      на самом деле не понимаю, как это происходит. Люди, которые... принимают эти
      законы, они правда не знают про Яндекс, например
    duration: 24.860000000000582
- speaker: Vodom
  total_time: 935.2
  reference_segment:
    stime: 3613.07
    etime: 3701.83
    text: К водопадам не очень хорошо отношусь. Но я могу сказать, что по этому пункту
      про дизайн-апфронт, что это такой троллевидный вброс, конечно. Но на самом деле
      он касается одной такой важной проблемы, мн
    duration: 88.75999999999976
- speaker: Svan
  total_time: 1167.7
  reference_segment:
    stime: 6048.13
    etime: 6131.11
    text: Нет, там на самом деле что-то очень политическое. Правда, тема, я буду стараться
      подбирать правильные слова. Там история же смешнее. Она смешнее в том, что Хабаровский
      суд потребовал от Ростелекома пр
    duration: 82.97999999999956
segments_to_extract:
- speaker: Umputun
  stime: 632.39
  etime: 717.94
  duration: 85.55000000000007
  type: reference
- speaker: SPEAKER_02
  stime: 1581.82
  etime: 1639.28
  duration: 57.460000000000036
  type: unknown
- speaker: SPEAKER_02
  stime: 1665.09
  etime: 1711.58
  duration: 46.49000000000001
  type: unknown
- speaker: SPEAKER_02
  stime: 2156.13
  etime: 2230.4
  duration: 74.26999999999998
  type: unknown
- speaker: Vodom
  stime: 3613.07
  etime: 3701.83
  duration: 88.75999999999976
  type: reference
- speaker: Marin_k_a
  stime: 4877.51
  etime: 4918.15
  duration: 40.63999999999942
  type: reference
- speaker: Ksenks
  stime: 6002.44
  etime: 6027.3
  duration: 24.860000000000582
  type: reference
- speaker: Svan
  stime: 6048.13
  etime: 6131.11
  duration: 82.97999999999956
  type: reference
comparisons:
- unknown: SPEAKER_02
  compare_with:
  - Umputun
  - Marin_k_a
  - Ksenks
  - Vodom
  - Svan
