episode: 397
unknown_speakers:
- speaker: Guest_Unknown_ep397_2
  total_time: 254.9
  segments:
  - stime: 564.75
    etime: 602.53
    text: Я бы не стал позиционировать эти решения как именно дипломент, это больше
      как система конфигураций. Дипломент в какой-то степени да, но опять же, если
      в двух проектах используются какие-либо... фреймв
    duration: 37.77999999999997
  - stime: 1076.3
    etime: 1100.47
    text: Ну, здесь... Не хочу показаться грубым, но мне кажется, тоже можно аргументировать
      доводом, что это мнимая переносимость. Как только человек начинает пользоваться
      Google или Amazon, у него вендерлог с
    duration: 24.170000000000073
  - stime: 5208.16
    etime: 5229.82
    text: 'Он не такой крутой. Ой, это очень сильно преувеличено. Возможно, наши иностранные
      гости нас не очень поймут, но вот в России есть такая сеть DNS называется, там
      продаются дисплеи с такой же матрицей, '
    duration: 21.659999999999854
- speaker: Guest_Unknown_ep397_1
  total_time: 1055.8
  segments:
  - stime: 6240.96
    etime: 6320.06
    text: Да, смотрите, я на самом деле считаю, что то, что они сделали это очень
      круто, это действительно поддержка FPGA в Xeon'ах должна появиться в будущих
      серверных. Суть в чем? Это, если правильно переводи
    duration: 79.10000000000036
  - stime: 2560.12
    etime: 2621.82
    text: Мне кажется, что выпустив его, они в основном для себя его делали. Что значит
      для себя? Не помню где, где-то я видел очень интересную фразу, что «Амазон научит
      вас покупать не в один клик, как это дел
    duration: 61.70000000000027
  - stime: 5141.8
    etime: 5182.66
    text: Но, с другой стороны, вот этого достаточно дешевого компьютера, его ведь
      хватит для большинства потребностей большинства пользователей. То есть, я вот
      сижу за Air достаточно старым, и при этом его для
    duration: 40.85999999999967
reference_speakers:
- speaker: Bobuk
  total_time: 201.6
  reference_segment:
    stime: 2064.93
    etime: 2110.33
    text: То есть, их люди, как правило, используют в комплексе с чем-то, что ими
      управляет. Citrix решения или там у Red Hat, по-моему, что-то есть. В любом
      случае всегда есть какая-то надстройка, которая упра
    duration: 45.40000000000009
- speaker: Umputun
  total_time: 3440.2
  reference_segment:
    stime: 3515.36
    etime: 3632.83
    text: У меня есть следующая тема. Понятно про скайп все. Ну ладно, обговоритесь,
      если вас заставляют. Наверное, в Линексе это какие-то проблемы. Какой-нибудь
      Ubuntu с какой-нибудь скайпом несовместимо окаже
    duration: 117.4699999999998
- speaker: Gray
  total_time: 1351.8
  reference_segment:
    stime: 4222.18
    etime: 4300.09
    text: Вот. Дальше. На самом деле, разработчик очень много рассказывает про то,
      что еще можно сделать. Можно, например, таким образом отвечать на рекламные
      акции. То есть, тебе приходит сообщение от спонсорс
    duration: 77.90999999999985
segments_to_extract:
- speaker: Guest_Unknown_ep397_2
  stime: 564.75
  etime: 602.53
  duration: 37.77999999999997
  type: unknown
- speaker: Guest_Unknown_ep397_2
  stime: 1076.3
  etime: 1100.47
  duration: 24.170000000000073
  type: unknown
- speaker: Bobuk
  stime: 2064.93
  etime: 2110.33
  duration: 45.40000000000009
  type: reference
- speaker: Guest_Unknown_ep397_1
  stime: 2560.12
  etime: 2621.82
  duration: 61.70000000000027
  type: unknown
- speaker: Umputun
  stime: 3515.36
  etime: 3632.83
  duration: 117.4699999999998
  type: reference
- speaker: Gray
  stime: 4222.18
  etime: 4300.09
  duration: 77.90999999999985
  type: reference
- speaker: Guest_Unknown_ep397_1
  stime: 5141.8
  etime: 5182.66
  duration: 40.85999999999967
  type: unknown
- speaker: Guest_Unknown_ep397_2
  stime: 5208.16
  etime: 5229.82
  duration: 21.659999999999854
  type: unknown
- speaker: Guest_Unknown_ep397_1
  stime: 6240.96
  etime: 6320.06
  duration: 79.10000000000036
  type: unknown
comparisons:
- unknown: Guest_Unknown_ep397_2
  compare_with:
  - Bobuk
  - Umputun
  - Gray
- unknown: Guest_Unknown_ep397_1
  compare_with:
  - Bobuk
  - Umputun
  - Gray
