episode: 403
unknown_speakers:
- speaker: SPEAKER_05
  total_time: 2113.6
  segments:
  - stime: 1020.12
    etime: 1172.8
    text: К Рио нужно отдельно сказать, что «да, я к TCP-соединениям готов». И вот
      давай тогда уже перейдем к TCP-соединениям, а то я все вокруг да около хожу.
      Значит, с TCP-соединением ситуация… С одной сторон
    duration: 152.67999999999995
  - stime: 2680.2
    etime: 2787.93
    text: Да, что-то такое. Я вот в это до конца пока еще не вник. Ну, в общем, идет
      стандартная вот такая вот движуха, когда open-source проект так разрастается
      всячески, обрастает сообществом, кодом и всякими
    duration: 107.73000000000002
  - stime: 3695.04
    etime: 3801.98
    text: Сейчас, погоди, значит, IOPS-ограничение, оно к пилупу не имеет отношения
      прямого, а IOPS имеет отношение, как это не странно звучит, к сегруппам. Пилуп
      я помянул, потому что вообще зашла речь про сто
    duration: 106.94000000000005
reference_speakers:
- speaker: Bobuk
  total_time: 2576.2
  reference_segment:
    stime: 4928.36
    etime: 5085.2
    text: Но у нас в этот раз просто очень прикольная победа. Дело в том, что большая
      часть людей, которые смотрели это все дело, которые участвовали, никто не ожидал
      такого результата. По-другому скажу. На сам
    duration: 156.84000000000015
- speaker: Umputun
  total_time: 2700.2
  reference_segment:
    stime: 4109.94
    etime: 4167.85
    text: Жарко. Речь идет о том, возвращаясь к нашей теме, что Раут-53 и, по слухам,
      одновременно гугловская балалайка, я не знаю, насколько одновременно, насколько
      синхронно, теперь являются регистраторами до
    duration: 57.910000000000764
- speaker: Marin_k_a
  total_time: 388.9
  reference_segment:
    stime: 4623.26
    etime: 4655.21
    text: Нет, ну, теперь, да, я помню, когда Инстаграм жил на Амазоне, и, по-моему,
      криков было, когда вот он уже лежал там час, наверное, то есть какое-то время,
      когда все уже успели покушать, один прием пищи
    duration: 31.949999999999818
- speaker: Ksenks
  total_time: 306.1
  reference_segment:
    stime: 7815.95
    etime: 7839.34
    text: которым это правда интересно. И вот эти две стороны, они никогда не поймут
      друг друга. Потому что те стороны, которые пиар и маркетинг, у них есть такие
      мысли, давайте там всюду запилим, не знаю, сись
    duration: 23.390000000000327
segments_to_extract:
- speaker: SPEAKER_05
  stime: 1020.12
  etime: 1172.8
  duration: 152.67999999999995
  type: unknown
- speaker: SPEAKER_05
  stime: 2680.2
  etime: 2787.93
  duration: 107.73000000000002
  type: unknown
- speaker: SPEAKER_05
  stime: 3695.04
  etime: 3801.98
  duration: 106.94000000000005
  type: unknown
- speaker: Umputun
  stime: 4109.94
  etime: 4167.85
  duration: 57.910000000000764
  type: reference
- speaker: Marin_k_a
  stime: 4623.26
  etime: 4655.21
  duration: 31.949999999999818
  type: reference
- speaker: Bobuk
  stime: 4928.36
  etime: 5085.2
  duration: 156.84000000000015
  type: reference
- speaker: Ksenks
  stime: 7815.95
  etime: 7839.34
  duration: 23.390000000000327
  type: reference
comparisons:
- unknown: SPEAKER_05
  compare_with:
  - Bobuk
  - Umputun
  - Marin_k_a
  - Ksenks
