episode: 429
unknown_speakers:
- speaker: SPEAKER_03
  total_time: 976.9
  segments:
  - stime: 4208.49
    etime: 4287.17
    text: Ну, потому что вы бы работали только в консоли, а так там можно, не знаю,
      в идее что-то показывать или там, не знаю, графики вместе рисовать или что-то
      делать. Но тут, собственно, проблема была, как в
    duration: 78.68000000000029
  - stime: 7270.62
    etime: 7328.67
    text: 'Не, ну вот, честно говоря, вот с одной стороны, я как бы понимаю вот этих
      вот людей, потому что Например, человеку старого поколения, как моей тёще, например,
      для неё каждое обновление Firefox, и тем '
    duration: 58.05000000000018
  - stime: 846.87
    etime: 878.42
    text: 'Тут еще маленькая ремарочка, что активно использовать как бы наружу. То
      есть если ты активно будешь использовать свои серваки, разворачивать, и много
      есть ситу инстансов, которые что-то процессят или '
    duration: 31.549999999999955
reference_speakers:
- speaker: Bobuk
  total_time: 2101.4
  reference_segment:
    stime: 7352.69
    etime: 7417.89
    text: Мы недалеко не с нуля. В смысле, в России доля Яндекс.Браузера выше 10%.
      Значительно выше 10%, если очень коротко. Просто есть разные измерители. По
      некоторым измерениям это около 20%, по некоторым ок
    duration: 65.20000000000073
- speaker: Alek.sys
  total_time: 142.0
  reference_segment:
    stime: 3129.08
    etime: 3144.41
    text: А ты, кстати, видел видеопрезентацию, по-моему, где-то на Цессе, что ли,
      LG Flex 2 такой гнутой, и у него очень прикольная задняя крышка, которая самая
      излечимая.
    duration: 15.329999999999927
- speaker: Umputun
  total_time: 2887.6
  reference_segment:
    stime: 943.52
    etime: 1103.45
    text: В один прекрасный день начинаю получать, это буквально было 3-4 дня назад,
      начинаю получать сигналы от систем наблюдения, которые говорят, что-то не так,
      что-то в лесу сдохло. Иду я смотреть. Ну, сдох
    duration: 159.93000000000006
- speaker: Ksenks
  total_time: 792.4
  reference_segment:
    stime: 282.11
    etime: 326.95
    text: По-моему, там за последние 90 дней каждый месяц у них было по миллиону,
      я так поняла. Просто раньше Амазон не говорил это открыто, и разные источники
      пытались выяснить, сколько у них таких пользовател
    duration: 44.839999999999975
segments_to_extract:
- speaker: Ksenks
  stime: 282.11
  etime: 326.95
  duration: 44.839999999999975
  type: reference
- speaker: SPEAKER_03
  stime: 846.87
  etime: 878.42
  duration: 31.549999999999955
  type: unknown
- speaker: Umputun
  stime: 943.52
  etime: 1103.45
  duration: 159.93000000000006
  type: reference
- speaker: Alek.sys
  stime: 3129.08
  etime: 3144.41
  duration: 15.329999999999927
  type: reference
- speaker: SPEAKER_03
  stime: 4208.49
  etime: 4287.17
  duration: 78.68000000000029
  type: unknown
- speaker: SPEAKER_03
  stime: 7270.62
  etime: 7328.67
  duration: 58.05000000000018
  type: unknown
- speaker: Bobuk
  stime: 7352.69
  etime: 7417.89
  duration: 65.20000000000073
  type: reference
comparisons:
- unknown: SPEAKER_03
  compare_with:
  - Bobuk
  - Alek.sys
  - Umputun
  - Ksenks
