episode: 445
unknown_speakers:
- speaker: SPEAKER_06
  total_time: 439.3
  segments:
  - stime: 2223.08
    etime: 2262.73
    text: Еще раз, вот смотри, у тебя есть элемент, этот элемент свернут в изначальном
      состоянии, когда тебе приходит ответ от сервера, и ты его рисуешь. Человек нажимает
      «развернуть его», а внутри есть еще пят
    duration: 39.65000000000009
  - stime: 6824.24
    etime: 6843.99
    text: Я скоро тоже не смогу ответить на этот вопрос, потому что тоже после 35
      уже скоро будет. Так отвечай бы стоя, если у тебя 5 минут осталось. Не знаю,
      мне кажется, что просто это какое-то клише, которое
    duration: 19.75
  - stime: 1301.55
    etime: 1321.2
    text: Я могу рассказать, зачем знакомые мои пользовались. У них система, которая
      должна опираться на известные библиотеки технологии, которые прошли какую-то
      проверку качества. И вот QT у них прошла проверк
    duration: 19.65000000000009
- speaker: SPEAKER_02
  total_time: 528.7
  segments:
  - stime: 1825.76
    etime: 1904.02
    text: Да, корневая концепция, что у тебя есть immutable данные, есть специальные
      структуры данных для JavaScript, собственно, библиотеки структуры данных, immutable
      совершенно, то есть ты можешь взять кусок
    duration: 78.25999999999999
  - stime: 1501.51
    etime: 1567.92
    text: Нет, вопрос не в том, как... То есть это же можно... То есть JavaScript
      не только функциональный, он еще и объект-ориентированный. Причем со всеми плохими
      последствиями, такими как глобальные ссылки н
    duration: 66.41000000000008
  - stime: 1575.51
    etime: 1636.98
    text: Так вот, React сделал все так, как было раньше в Web 1.0, только это выглядит
      для разработчика как Web 1.0, то есть, грубо говоря, у тебя есть тот же самый
      паттерн, когда ты берешь данные. и просовыва
    duration: 61.47000000000003
reference_speakers:
- speaker: Umputun
  total_time: 2963.6
  reference_segment:
    stime: 5790.8
    etime: 5898.2
    text: Недавно был, не недавно, вчера буквально, у нас с утра был телефонный разговор
      с моей корпорацией. Представляете, мы теперь их заказчики. Ну, мы всегда были
      заказчики одного из их сервисов. Но это пер
    duration: 107.39999999999964
- speaker: Gray
  total_time: 450.2
  reference_segment:
    stime: 5013.89
    etime: 5042.2
    text: Нет, смотрите, тогда здесь, конечно, ровно Тогда вот первый пункт превращается
      Не вы работаете с генеральным директором А вы имеете шанс Когда-нибудь встретить
      на работе Этого генерального директора В
    duration: 28.30999999999949
- speaker: Ksenks
  total_time: 1882.8
  reference_segment:
    stime: 960.1
    etime: 1107.87
    text: Идея какая? Apple, точно не помню, для какой MacOS, они заинтродюсили гарбич-коллектор.
      То есть это была фича, это был большой дил, и даже для iOS была команда, которая
      писала гарбич-коллекшн-поддержк
    duration: 147.76999999999987
segments_to_extract:
- speaker: Ksenks
  stime: 960.1
  etime: 1107.87
  duration: 147.76999999999987
  type: reference
- speaker: SPEAKER_06
  stime: 1301.55
  etime: 1321.2
  duration: 19.65000000000009
  type: unknown
- speaker: SPEAKER_02
  stime: 1501.51
  etime: 1567.92
  duration: 66.41000000000008
  type: unknown
- speaker: SPEAKER_02
  stime: 1575.51
  etime: 1636.98
  duration: 61.47000000000003
  type: unknown
- speaker: SPEAKER_02
  stime: 1825.76
  etime: 1904.02
  duration: 78.25999999999999
  type: unknown
- speaker: SPEAKER_06
  stime: 2223.08
  etime: 2262.73
  duration: 39.65000000000009
  type: unknown
- speaker: Gray
  stime: 5013.89
  etime: 5042.2
  duration: 28.30999999999949
  type: reference
- speaker: Umputun
  stime: 5790.8
  etime: 5898.2
  duration: 107.39999999999964
  type: reference
- speaker: SPEAKER_06
  stime: 6824.24
  etime: 6843.99
  duration: 19.75
  type: unknown
comparisons:
- unknown: SPEAKER_06
  compare_with:
  - Umputun
  - Gray
  - Ksenks
- unknown: SPEAKER_02
  compare_with:
  - Umputun
  - Gray
  - Ksenks
