episode: 462
unknown_speakers:
- speaker: SPEAKER_05
  total_time: 209.6
  segments:
  - stime: 1111.07
    etime: 1146.09
    text: 'Я встану на защиту их. Они в последнее время, кажется, большие молодцы,
      что они сделали для iOS. То есть они как-то перестали централизовываться вокруг
      своей инфраструктуры, вокруг своей платформы. И '
    duration: 35.01999999999998
  - stime: 1785.77
    etime: 1806.14
    text: Я другой кейс приведу. Хаббр, Гик Таймс, вся сеть тематических медиа. Тебе
      высвечивают большие баннеры и говорят, что если хочешь, можешь не смотреть на
      Шуриком, а вот нажми на крестик, мы тебя больше
    duration: 20.37000000000012
  - stime: 6063.87
    etime: 6076.91
    text: А как же такой кейс, который в «Силиконовой долине» описывали, ну в сериале
      я имею в виду, что ты узнаешь о том, что упадешь без сознания, либо что тебя
      вот-вот паническая атака настигнет до того, как
    duration: 13.039999999999964
reference_speakers:
- speaker: Bobuk
  total_time: 3028.0
  reference_segment:
    stime: 1495.16
    etime: 1604.93
    text: 'То есть, они вместе... Я думаю, что он просто договорился с ребятами из
      Остери о том, что можно делиться этими данными и все такое. Но дальше произошло
      прикольное. У него сайт и подкаст, и все, что с '
    duration: 109.76999999999998
- speaker: Umputun
  total_time: 2942.6
  reference_segment:
    stime: 5574.64
    etime: 5680.96
    text: Я к чему? Вы помните страшные истории? Это я пока, Ксюша, думаю о следующей
      теме. Страшная история о том, как человек оставил на Амазоне критический отзыв,
      а потом за ним пришли трое с автоматами. Ну,
    duration: 106.31999999999971
- speaker: Ksenks
  total_time: 1115.0
  reference_segment:
    stime: 8029.73
    etime: 8135.52
    text: Да, есть еще вопрос ко мне. По поводу того, волнует ли меня дефрагментация
      Apple устройств. На чем я не спешу? Нет, ну вообще волнует, и я об этом уже
      говорила. Мне не нравится, что очень много разных
    duration: 105.79000000000087
- speaker: sergey_selectel_462
  total_time: 121.4
  reference_segment:
    stime: 3218.17
    etime: 3242.99
    text: По наружу у нас есть, собственно, два способа. Первый – это простой, просто
      публичный влан с белыми адресами. И есть способ с плавающими IP-адресами. Это
      аналог Elastic IP, соответственно. То есть, пр
    duration: 24.81999999999971
segments_to_extract:
- speaker: SPEAKER_05
  stime: 1111.07
  etime: 1146.09
  duration: 35.01999999999998
  type: unknown
- speaker: Bobuk
  stime: 1495.16
  etime: 1604.93
  duration: 109.76999999999998
  type: reference
- speaker: SPEAKER_05
  stime: 1785.77
  etime: 1806.14
  duration: 20.37000000000012
  type: unknown
- speaker: sergey_selectel_462
  stime: 3218.17
  etime: 3242.99
  duration: 24.81999999999971
  type: reference
- speaker: Umputun
  stime: 5574.64
  etime: 5680.96
  duration: 106.31999999999971
  type: reference
- speaker: SPEAKER_05
  stime: 6063.87
  etime: 6076.91
  duration: 13.039999999999964
  type: unknown
- speaker: Ksenks
  stime: 8029.73
  etime: 8135.52
  duration: 105.79000000000087
  type: reference
comparisons:
- unknown: SPEAKER_05
  compare_with:
  - Bobuk
  - Umputun
  - Ksenks
  - sergey_selectel_462
