episode: 466
unknown_speakers:
- speaker: SPEAKER_02
  total_time: 705.0
  segments:
  - stime: 2287.44
    etime: 2330.64
    text: Кстати, не знаю, но, по крайней мере, из твоих подкастов сложилось впечатление,
      что ты прям был так доволен Red Hat, ты так нежно всегда о нем отзывался, что
      типа вот, пришли новые сервера, накатил мо
    duration: 43.19999999999982
  - stime: 6211.86
    etime: 6249.7
    text: Вот смотри, я не знаю, как я бы сделал, то есть есть вот старый UI, запихиваем
      туда процедуру какой-нибудь по миграции, которая, если пользователь заходит
      туда в старый UI, там где-то в фоне запускает
    duration: 37.840000000000146
  - stime: 1775.47
    etime: 1803.83
    text: Ну, очень интересно, почему ты считаешь, что для стартапа, который что-то
      сделал в технологической области, покупка более большим вендором – это плохой
      вариант? Но, тем не менее, в наше интернет ворва
    duration: 28.3599999999999
reference_speakers:
- speaker: Bobuk
  total_time: 2579.7
  reference_segment:
    stime: 4669.86
    etime: 4767.54
    text: Ну, конечно, не только на лице. Это что? Конечно, в этом вся идея была.
      Почему девочки вкладывались, как ты думаешь? Потому что, чтобы мужиков брить,
      что ли, за сейчас? Короче, история простая. Ребята
    duration: 97.68000000000029
- speaker: Alek.sys
  total_time: 144.9
  reference_segment:
    stime: 6153.06
    etime: 6169.45
    text: Погодите, это подкаст тех, кто занимается бигдейтой или где, я что-то не
      понимаю. То есть вы предлагаете остановить проект, например, наши базы терабайты,
      и эти терабайты перекладывать вы будете неско
    duration: 16.389999999999418
- speaker: Umputun
  total_time: 3439.3
  reference_segment:
    stime: 1832.61
    etime: 1915.82
    text: Если смотреть с точки зрения людей, которые получили, не знаю, много или
      какие-то деньги, то за них можно только порадоваться. Но, собственно, моя цель
      не обогатить этих людей. Одна из моих целей по ж
    duration: 83.21000000000004
- speaker: Ksenks
  total_time: 710.5
  reference_segment:
    stime: 5252.01
    etime: 5300.94
    text: Да, и весь интернет был настолько просто зол на Марка, и что Марка там...
      вернул им 3 доллара, и теперь можно пользоваться приложением, но оно никогда
      не обновится. Ну, в общем, странно, что люди были
    duration: 48.92999999999938
segments_to_extract:
- speaker: SPEAKER_02
  stime: 1775.47
  etime: 1803.83
  duration: 28.3599999999999
  type: unknown
- speaker: Umputun
  stime: 1832.61
  etime: 1915.82
  duration: 83.21000000000004
  type: reference
- speaker: SPEAKER_02
  stime: 2287.44
  etime: 2330.64
  duration: 43.19999999999982
  type: unknown
- speaker: Bobuk
  stime: 4669.86
  etime: 4767.54
  duration: 97.68000000000029
  type: reference
- speaker: Ksenks
  stime: 5252.01
  etime: 5300.94
  duration: 48.92999999999938
  type: reference
- speaker: Alek.sys
  stime: 6153.06
  etime: 6169.45
  duration: 16.389999999999418
  type: reference
- speaker: SPEAKER_02
  stime: 6211.86
  etime: 6249.7
  duration: 37.840000000000146
  type: unknown
comparisons:
- unknown: SPEAKER_02
  compare_with:
  - Bobuk
  - Alek.sys
  - Umputun
  - Ksenks
