episode: 506
unknown_speakers:
- speaker: ruslan_unknown
  total_time: 145.3
  segments:
  - stime: 1388.63
    etime: 1425.35
    text: Так, кто там еще говорил? Хочется надеяться, что, например, Джава теряет
      свои места, не потому что он такая хорошая или там си-хорошая, а потому что
      есть другие языки, как Коклин или там Скалла, Груви
    duration: 36.7199999999998
  - stime: 1530.68
    etime: 1559.12
    text: Конечно же, реально. Причем последняя идея даже начала подсказывать основные
      моменты, на которых новички падают. То, что надо классы делать open, потому
      что в Kotlin все файнал по дефолту. То есть кла
    duration: 28.439999999999827
  - stime: 995.06
    etime: 1019.31
    text: Да, смотрели, и это очень удивительно, что R выше, чем JavaScript. Вот я
      никогда не поверю, не поверю, и, наверное, так и нету. То есть язык, который
      для анализа данных создан очень маленьким кругом л
    duration: 24.25
- speaker: SPEAKER_04
  total_time: 1034.6
  segments:
  - stime: 2330.36
    etime: 2389.31
    text: Кратко, версия очень... Это их система. Для того, чтобы выполнять потоковый
      MapReduce, ну, это очень сильное упрощение. Для того, чтобы... У тебя есть условно
      в кавычках, ну, не в кавычках, просто окн
    duration: 58.94999999999982
  - stime: 3077.49
    etime: 3126.33
    text: 'Но потом, видимо, это отвалилось. По коммитам можно посмотреть, естественно,
      как оно там было. Поэтому теоретически, наверное, где-то использовался. То есть
      у них есть живая миграция? Ну, скажем так, '
    duration: 48.840000000000146
  - stime: 3382.01
    etime: 3423.42
    text: 'Что-то еще там интересное есть? Ну, я так быстро пролистал. Там самое главное,
      это, естественно, переезд на новое ядро. Немножко обновили стандартные утилиты.
      Проинтегрировали с Лимбиртом. Все знают, '
    duration: 41.409999999999854
- speaker: SPEAKER_06
  total_time: 382.9
  segments:
  - stime: 2067.92
    etime: 2101.91
    text: Потому что когда вы делаете инфраструктуру под себя, она затачивается у
      вас под свои параметры. То есть под свои какие-то бизнес-кейсы. И это все работает.
      Но когда вы хотите сделать это более обобщен
    duration: 33.98999999999978
  - stime: 5622.77
    etime: 5652.95
    text: Когда его вытаскивают, он весь такой красивый, в том, что было в колодце,
      и начинает возмущаться, подводят к нему переводчика, он начинает объяснять,
      что как же так, как так можно, ну почему тут никак
    duration: 30.17999999999938
  - stime: 2458.73
    etime: 2480.76
    text: Будет хорошо. Я в этом действительно не очень сильно специалист. Мой проект
      связан с этим, но я не так глубоко в нем увяз. Но идея того, что вы можете писать
      пайплайны на каком-то своем одном языке, п
    duration: 22.0300000000002
reference_speakers:
- speaker: Bobuk
  total_time: 142.2
  reference_segment:
    stime: 1105.65
    etime: 1137.7
    text: И, соответственно, логично звучит утверждение о том, что если есть много
      людей, которые не знают, как писать на языке, но очень хотят, потому что это
      хайп, потому что это слышно, и это можно продаться
    duration: 32.049999999999955
- speaker: Alek.sys
  total_time: 479.7
  reference_segment:
    stime: 764.83
    etime: 800.26
    text: Перевивать очень трудно, лаг большой, непонятно, когда остановиться и когда
      начинать. У меня, может быть, другая точка зрения, почему такие цифры возникли,
      такие числа появились в этом отчете. Тут нуж
    duration: 35.42999999999995
- speaker: Gray
  total_time: 3186.0
  reference_segment:
    stime: 7801.15
    etime: 8008.99
    text: Ну... Не знаю. А, вот могу ответить на вопрос, который тут задают с вопросом,
      что стало с Яндекс.Островами. Давайте, может быть, на этом и закончим. Тут написано,
      что злые языки утверждают, что экспер
    duration: 207.84000000000015
- speaker: Ksenks
  total_time: 1590.6
  reference_segment:
    stime: 1745.34
    etime: 1854.57
    text: Ну, я была близко, я уже далеко. Да. Мне кажется, что этот квартал для всех
      компаний был достаточно хорошим. Просто все показали прибыли, которые выше ожиданий.
      И это, мне кажется, значит не только, ч
    duration: 109.23000000000002
- speaker: EldarMurtazin
  total_time: 513.7
  reference_segment:
    stime: 3663.9
    etime: 3701.46
    text: 'Там стоят на 15 машинках, кажется, каждой машинке по 5 или более инстансов
      нашего аппликейшна, которые должны как бы друг с другом общаться, копии с копией.
      И мы имитируем просто сплитбрейн, там есть '
    duration: 37.559999999999945
segments_to_extract:
- speaker: Alek.sys
  stime: 764.83
  etime: 800.26
  duration: 35.42999999999995
  type: reference
- speaker: ruslan_unknown
  stime: 995.06
  etime: 1019.31
  duration: 24.25
  type: unknown
- speaker: Bobuk
  stime: 1105.65
  etime: 1137.7
  duration: 32.049999999999955
  type: reference
- speaker: ruslan_unknown
  stime: 1388.63
  etime: 1425.35
  duration: 36.7199999999998
  type: unknown
- speaker: ruslan_unknown
  stime: 1530.68
  etime: 1559.12
  duration: 28.439999999999827
  type: unknown
- speaker: Ksenks
  stime: 1745.34
  etime: 1854.57
  duration: 109.23000000000002
  type: reference
- speaker: SPEAKER_06
  stime: 2067.92
  etime: 2101.91
  duration: 33.98999999999978
  type: unknown
- speaker: SPEAKER_04
  stime: 2330.36
  etime: 2389.31
  duration: 58.94999999999982
  type: unknown
- speaker: SPEAKER_06
  stime: 2458.73
  etime: 2480.76
  duration: 22.0300000000002
  type: unknown
- speaker: SPEAKER_04
  stime: 3077.49
  etime: 3126.33
  duration: 48.840000000000146
  type: unknown
- speaker: SPEAKER_04
  stime: 3382.01
  etime: 3423.42
  duration: 41.409999999999854
  type: unknown
- speaker: EldarMurtazin
  stime: 3663.9
  etime: 3701.46
  duration: 37.559999999999945
  type: reference
- speaker: SPEAKER_06
  stime: 5622.77
  etime: 5652.95
  duration: 30.17999999999938
  type: unknown
- speaker: Gray
  stime: 7801.15
  etime: 8008.99
  duration: 207.84000000000015
  type: reference
comparisons:
- unknown: ruslan_unknown
  compare_with:
  - Bobuk
  - Alek.sys
  - Gray
  - Ksenks
  - EldarMurtazin
- unknown: SPEAKER_04
  compare_with:
  - Bobuk
  - Alek.sys
  - Gray
  - Ksenks
  - EldarMurtazin
- unknown: SPEAKER_06
  compare_with:
  - Bobuk
  - Alek.sys
  - Gray
  - Ksenks
  - EldarMurtazin
