episode: 994
unknown_speakers:
- speaker: Guest_Unknown
  total_time: 896.3
  segments:
  - stime: 1095.48
    etime: 1179.77
    text: Ну, типа такая же библиотека, ну, как ты написал. Просто в чем проблема?
      В том, что если у меня, например, есть уже асинхронное приложение, ну, например,
      асинхронный веб-сервер, то, что обычно все и 9
    duration: 84.28999999999996
  - stime: 5197.68
    etime: 5259.57
    text: Смотрите, а нет такого опасения, мне кажется, вы немножечко, возможно, с
      разных сторон про разные кейсы говорите. То есть пример легкий в том, что ты
      можешь прийти в незнакомый проект, за часик накида
    duration: 61.88999999999942
  - stime: 4200.61
    etime: 4252.25
    text: Веселое. Ну, лично... Ну, не совсем. Лично у меня прям таких историй не
      было, но было чуть-чуть другое, как я сбоку видел. В одной из компаний, в которых
      я работал, Так случилось, что искали новых фро
    duration: 51.64000000000033
reference_speakers:
- speaker: Alek.sys
  total_time: 2102.7
  reference_segment:
    stime: 499.66
    etime: 561.85
    text: Причем знаешь, насколько они конкурентные? Что, например, ты можешь из синхронного
      кода вызывать... Из асинхронного кода вызывать любой. То есть в том числе синхронный
      и в том числе блокирующий. Узнат
    duration: 62.19
- speaker: Umputun
  total_time: 4388.2
  reference_segment:
    stime: 5782.1
    etime: 5903.7
    text: В моих поисках ошибок с AI стал возможным там, где... Вот как у меня раньше,
      чтобы ты понимала, Ксюша, как раньше у меня выглядел поиск... Вот приходит ко
      мне тетка и говорит, заказчик говорит, опции,
    duration: 121.59999999999945
- speaker: Ksenks
  total_time: 1534.2
  reference_segment:
    stime: 4401.99
    etime: 4514.91
    text: Ну, короче, его главная идея это в том, что даже если мы предположим, что
      AI нам упростит именно написание кода на 90%, так как написание кода не есть
      все, что мы делаем в работе, Как бы реальные улуч
    duration: 112.92000000000007
segments_to_extract:
- speaker: Alek.sys
  stime: 499.66
  etime: 561.85
  duration: 62.19
  type: reference
- speaker: Guest_Unknown
  stime: 1095.48
  etime: 1179.77
  duration: 84.28999999999996
  type: unknown
- speaker: Guest_Unknown
  stime: 4200.61
  etime: 4252.25
  duration: 51.64000000000033
  type: unknown
- speaker: Ksenks
  stime: 4401.99
  etime: 4514.91
  duration: 112.92000000000007
  type: reference
- speaker: Guest_Unknown
  stime: 5197.68
  etime: 5259.57
  duration: 61.88999999999942
  type: unknown
- speaker: Umputun
  stime: 5782.1
  etime: 5903.7
  duration: 121.59999999999945
  type: reference
comparisons:
- unknown: Guest_Unknown
  compare_with:
  - Alek.sys
  - Umputun
  - Ksenks
